In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("./dataset/credit_data.csv")
df.head()

clientid        income        age         loan       LTI  default
0         1  66155.925095  59.017015  8106.532131  0.122537        0
1         2  34415.153966  48.117153  6564.745018  0.190752        0
2         3  57317.170063  63.108049  8020.953296  0.139940        0
3         4  42709.534201  45.751972  6103.642260  0.142911        0
4         5  66952.688845  18.584336  8770.099235  0.130989        1

In [4]:
features = df[["income", "age", "loan"]]
target = df.default

In [6]:
feature_train, feature_test, target_train, target_test = train_test_split(features, target, test_size=0.3)

In [7]:
model = GaussianNB()

In [8]:
fittedModel = model.fit(feature_train,target_train)

In [9]:
pred = fittedModel.predict(feature_test)

In [10]:
print(confusion_matrix(target_test, pred))
print(accuracy_score(target_test, pred))

[[500  14]
 [ 33  53]]
0.9216666666666666


In [11]:
features.corr()

income       age      loan
income  1.000000 -0.034984  0.441117
age    -0.034984  1.000000  0.006561
loan    0.441117  0.006561  1.000000

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [14]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

In [15]:
print((X*X.T).A)

[[1.         0.64692568 0.30777187 1.        ]
 [0.64692568 1.         0.22523955 0.64692568]
 [0.30777187 0.22523955 1.         0.30777187]
 [1.         0.64692568 0.30777187 1.        ]]
