In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import datasets

In [2]:
data = datasets.load_iris()

In [4]:
features = data.data
targets = data.target

In [18]:
feature_train,feature_test,target_train,target_test = train_test_split(features, targets, test_size=0.2)

In [19]:
model = RandomForestClassifier(n_estimators=1000,max_features='sqrt')
fitted_model = model.fit(feature_train, target_train)
pred = fitted_model.predict(feature_test)

In [20]:
print(confusion_matrix(target_test, pred))
print(accuracy_score(target_test, pred))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  2  9]]
0.9333333333333333


In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_validate

In [22]:
df = pd.read_csv("data/credit_data.csv")
df.head()

clientid        income        age         loan       LTI  default
0         1  66155.925095  59.017015  8106.532131  0.122537        0
1         2  34415.153966  48.117153  6564.745018  0.190752        0
2         3  57317.170063  63.108049  8020.953296  0.139940        0
3         4  42709.534201  45.751972  6103.642260  0.142911        0
4         5  66952.688845  18.584336  8770.099235  0.130989        1

In [23]:
features = df[["income", "age", "loan"]]
targets = df.default

In [24]:
X = np.array(features).reshape(-1,3)
y = np.array(targets)

In [28]:
model = RandomForestClassifier(n_estimators=100)

In [29]:
preds = cross_validate(model, X, y, cv=10)

In [30]:
print(np.mean(preds["test_score"]))

0.9909999999999999
