In [1]:
from keras.datasets import cifar10
import numpy as np
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.optimizers import SGD
from keras.layers import BatchNormalization

In [2]:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [3]:
print(X_train)

[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

In [4]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [5]:
X_train = X_train / 255.0
X_test = X_test / 255.0

In [8]:
model = Sequential()

model.add(Conv2D(32,(3,3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(32,32,3)))
model.add(BatchNormalization())

model.add(Conv2D(32,(3,3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))

model.add(Conv2D(64,(3,3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())

model.add(Conv2D(64,(3,3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))

model.add(Conv2D(128,(3,3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())

model.add(Conv2D(128,(3,3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))
model.add(Flatten())

model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))

C:\Users\Admin\keras\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
optimizer = SGD(learning_rate=0.001, momentum=0.95)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_data=(X_test, y_test), verbose=2)
model.result = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy of CNN model : %s' % (model.result[1]* 100.0))

Epoch 1/50
782/782 - 90s - 115ms/step - accuracy: 0.4207 - loss: 1.5974 - val_accuracy: 0.5203 - val_loss: 1.3263
Epoch 2/50
782/782 - 93s - 119ms/step - accuracy: 0.5648 - loss: 1.2059 - val_accuracy: 0.5893 - val_loss: 1.1490
Epoch 3/50
782/782 - 97s - 124ms/step - accuracy: 0.6270 - loss: 1.0374 - val_accuracy: 0.6439 - val_loss: 1.0068
Epoch 4/50
782/782 - 96s - 123ms/step - accuracy: 0.6688 - loss: 0.9344 - val_accuracy: 0.6987 - val_loss: 0.8617
Epoch 5/50
782/782 - 101s - 129ms/step - accuracy: 0.6983 - loss: 0.8514 - val_accuracy: 0.6780 - val_loss: 0.9355
Epoch 6/50
782/782 - 99s - 126ms/step - accuracy: 0.7205 - loss: 0.7883 - val_accuracy: 0.7127 - val_loss: 0.8315
Epoch 7/50
782/782 - 100s - 128ms/step - accuracy: 0.7402 - loss: 0.7360 - val_accuracy: 0.7229 - val_loss: 0.7968
Epoch 8/50
782/782 - 102s - 131ms/step - accuracy: 0.7557 - loss: 0.6904 - val_accuracy: 0.7309 - val_loss: 0.7730
Epoch 9/50
782/782 - 99s - 126ms/step - accuracy: 0.7709 - loss: 0.6502 - val_accurac